apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: skill-micro
  labels:
    app: gateway-service
spec:
  type: ClusterIP
  selector:
    app: gateway-service
  ports:
  - name: http
    port: 3003
    targetPort: 3003
